xrandr --output Virtual-1 --mode 1366x768 &

picom -f &

nitrogen --restore &

case "$1" in
	xmonad)
		exec ~/.local/share/xmonad/xmonad-x86_64-linux &
		;;
	exwm)
		export _JAVA_AWT_WM_NONREPARENTING=1
		xsetroot -cursor_name left_ptr
		dbus-launch --exit-with-session emacs -mm --debug-init
		;;
	wm)
		wew | yawee &
		;;
	pipeworld)
		arcan pipeworld &
		;;
	awesome)
		awesome &
		;;
	stumpwm)
		stumpwm &
		;;
	*)
		exec dwm &
		;;
esac

exec sxhkd &
sh ~/bin/xsetloop
