#!/bin/sh

source $HOME/.bashrc

export PATH="$HOME/bin:$PATH"
export PS1="[ \[\e[31;1m\]\h\[\e[0m\] \[\e[36;3m\]\W\[\e[0m\] ] "

mkdir_cd() {
	mkdir -p $1
	cd $1
}

git_branch_checkout() {
	git branch $1
	git checkout $1
}

if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    source $HOME/.bash-git-prompt/gitprompt.sh
fi

eval "$(pandoc --bash-completion)"
eval "$(rclone completion bash)"

alias ls='ls --color=auto'
alias ll='ls -la'
alias mkcd='mkdir_cd'
alias tmux-new='tmux new-window -c "#{pane_current_path}"'
alias glgoa='git log --graph --oneline --all'
alias gibc='git_branch_checkout'
alias gs='git status'
